#./scripts/llnerf-datasets/book.sh
#./scripts/llnerf-datasets/campus-path.sh
#./scripts/llnerf-datasets/cart.sh
#./scripts/llnerf-datasets/D5.sh
#./scripts/llnerf-datasets/flower.sh
#./scripts/llnerf-datasets/hall.sh
#./scripts/llnerf-datasets/moto.sh
#./scripts/llnerf-datasets/palm.sh
#./scripts/llnerf-datasets/path.sh
#./scripts/llnerf-datasets/room.sh
#./scripts/llnerf-datasets/shrub.sh
./scripts/llnerf-datasets/still2.sh
./scripts/llnerf-datasets/still3.sh
./scripts/llnerf-datasets/still4.sh
./scripts/llnerf-datasets/wall.sh
./scripts/llnerf-datasets/white-chair.sh